module.exports.aCreate = require('./a_controler')
module.exports.bCreate = require('./b_controler')
module.exports.cCreate = require('./c_controler')
module.exports.dCreate = require('./d_controler')
module.exports.xCreate = require('./e_controler')
module.exports.fCreate = require('./f_controler')
module.exports.kCreate = require('./k_controler')
module.exports.gCreate = require('./g_controler')
module.exports.hCreate = require('./h_controler')
module.exports.iCreate = require('./i_controler')
module.exports.jCreate = require('./j_controler')
module.exports.lCreate = require('./l_controler')
module.exports.nCreate = require('./n_controler')
module.exports.mCreate = require('./m_controler')
module.exports.oCreate = require('./o_controler')
module.exports.korianCreate = require('./korian8_controler')
module.exports.hollywoodCreate = require('./hollywood9_controler')
 module.exports.bollywoodCreate = require('./bollywood_controler')
module.exports.userCreate = require('./user11_controler')
module.exports.horrerCreate = require('./horrer12_controler')
module.exports.actionCreate = require('./action_controller')
module.exports.serialCreate = require('./serial6_controller')
module.exports.pCreate = require('./p_controler')
module.exports.qCreate = require('./q_controler')
module.exports.rCreate = require('./r_controler')


