const express = require('express')
const aRoutes = require('./a_routes')
const cRoutes = require('./c_routes')
const bRoutes = require('./b_routes')
const dRoutes = require('./d_routes')
const xRoutes = require('./e_routes')
const fRoutes = require('./f_routes')
const kRoutes = require('./k_routes')
const gRoutes = require('./g_routes')
const hRoutes = require('./h_routes')
const iRoutes = require('./i_routes')
const jRoutes = require('./j_routes')
const lRoutes = require('./l_routes')
const mRoutes = require('./m_routes')
const nRoutes = require('./n_routes')
const oRoutes = require('./o_routes')
const korianRoutes = require('./korian8_routes')
const hollywoodRoutes = require('./hollywood9_routes')
const bollywoodRoutes = require('./bollywood_routes')
const horrerRoutes = require('./horrer12_routes')
const userRoutes = require('./user11_routes')
const actionRoutes = require('./action_routes')
const serial_routes = require('./serial6_routes')
const pRoutes = require('./p_routes')
const qRoutes = require('./q_routes')
const rRoutes = require('./r_routes')



const router= express()
router.use('/a',aRoutes)
router.use('/c',cRoutes)
router.use('/b',bRoutes)
router.use('/d',dRoutes)
router.use('/x',xRoutes)
router.use('/f',fRoutes)
router.use('/k',kRoutes)
router.use('/g',gRoutes)
router.use('/h',hRoutes)
router.use('/i',iRoutes)
router.use('/j',jRoutes)
router.use('/l',lRoutes)
router.use('/m',mRoutes)
router.use('/n',nRoutes)
router.use('/o',oRoutes)
router.use('/korian',korianRoutes)
router.use('/hollywood',hollywoodRoutes)
router.use('/bollywood',bollywoodRoutes)
router.use('/user',userRoutes)
router.use('/horrer',horrerRoutes)
router.use('/action',actionRoutes)
router.use('/serial',serial_routes)
router.use('/p',pRoutes)
router.use('/q',qRoutes)
router.use('/r',rRoutes)




module.exports = router
